name: "Model x"
spatial resolution: 
variable spatial resolution: Yes
dimensionality: "0D" #Should be one of the following 0D, 1D, 2D or 3D
temporal resolution:
  value: 1
  units: "days"
variable temporal resolution: No
input data:
  - {name: "value 1", description: "", units: "m^2"}
  - {name: "value 2", description: "", units: "celsius"}
output data:
  - {name: "value 3", description: "", units: "km/h"}
  - {name: "value 4", description: "", units: "celsius"}
calibration variables:
  - {name: "calibration value 1", description: "", units: ""}
computational requirements: "Requires GPU"